id: 'ttsky25b'
name: 'Tiny Tapeout SKY 25b'
pdk: 'sky130A'
end_date: '2025-11-10'
project_dir: 'projects'
top_level_macro: 'openframe_project_wrapper'
powered_netlists: true

datasheet_config:
  theme_override_colour: tt.colours.THEME_SKY_BLUE
  link_override_colour: tt.colours.THEME_SKY_BLUE

  include:
    - docs/chip_map.typ
    # - docs/funding.typ
