id: 'ttsky26a'
name: 'Tiny Tapeout SKY 26a'
pdk: 'sky130A'
end_date: '2026-05-11'
project_dir: 'projects'
top_level_macro: 'openframe_project_wrapper'
powered_netlists: true

datasheet_config:
  theme_override_colour: tt.colours.THEME_SKY_BLUE
  link_override_colour: tt.colours.THEME_SKY_BLUE

  artwork:
    - {id: TT_POCA_01_A, rotate: -90deg}
    - {id: TT_POCA_01_B, rotate: -90deg}
    - {id: TT_POCA_01_C, rotate: -90deg}
    - {id: TT_POCA_01_D, rotate: -90deg}
    - {id: TT_POCA_01_E, rotate: -90deg}
    - {id: TT_POCA_01_F, rotate: 90deg}
    - {id: TT_POCA_01_G, rotate: 90deg}
    - {id: TT_POCA_01_H, rotate: -90deg}
    - {id: TT_POCA_01_I, rotate: 90deg}

  include:
    - docs/chip_map.typ
    - docs/funding.typ
